// <auto-generated />
using System;
using Aplikacija.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplikacija.Migrations
{
    [DbContext(typeof(AplikacijaDbContext))]
    [Migration("20260412102155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplikacija.Models.Odjel", b =>
                {
                    b.Property<int>("OdjelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdjelId"));

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdjelId");

                    b.ToTable("Odjeli");
                });

            modelBuilder.Entity("Aplikacija.Models.Projekat", b =>
                {
                    b.Property<int>("ProjekatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjekatId"));

                    b.Property<decimal?>("BudzetUSD")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("DatumKraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjekatId");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikId"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdjelId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlataMonthly")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OdjelId");

                    b.ToTable("Zaposlenici");
                });

            modelBuilder.Entity("Aplikacija.Models.ZaposlenikProjekat", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .HasColumnType("int");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<int>("SatiNaTjednu")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId", "ProjekatId");

                    b.HasIndex("ProjekatId");

                    b.ToTable("ZaposlenikProjekti");
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.HasOne("Aplikacija.Models.Odjel", "Odjel")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("OdjelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("Aplikacija.Models.ZaposlenikProjekat", b =>
                {
                    b.HasOne("Aplikacija.Models.Projekat", "Projekat")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikacija.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ZaposlenikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("Aplikacija.Models.Odjel", b =>
                {
                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("Aplikacija.Models.Projekat", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });
#pragma warning restore 612, 618
        }
    }
}
