// <auto-generated />
using System;
using Aplikacija.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplikacija.Migrations
{
    [DbContext(typeof(AplikacijaDbContext))]
    partial class AplikacijaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aplikacija.Models.Odjel", b =>
                {
                    b.Property<int>("OdjelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdjelId"));

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdjelId");

                    b.ToTable("Odjeli");

                    b.HasData(
                        new
                        {
                            OdjelId = 1,
                            Lokacija = "Sarajevo",
                            Naziv = "HR"
                        },
                        new
                        {
                            OdjelId = 2,
                            Lokacija = "Mostar",
                            Naziv = "Finansije"
                        },
                        new
                        {
                            OdjelId = 3,
                            Lokacija = "Zenica",
                            Naziv = "IT"
                        });
                });

            modelBuilder.Entity("Aplikacija.Models.Projekat", b =>
                {
                    b.Property<int>("ProjekatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjekatId"));

                    b.Property<decimal?>("BudzetUSD")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("DatumKraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetak")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjekatId");

                    b.ToTable("Projekti");

                    b.HasData(
                        new
                        {
                            ProjekatId = 1,
                            BudzetUSD = 50000m,
                            DatumKraj = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Web App"
                        },
                        new
                        {
                            ProjekatId = 2,
                            BudzetUSD = 30000m,
                            DatumKraj = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Mobile App"
                        },
                        new
                        {
                            ProjekatId = 3,
                            BudzetUSD = 70000m,
                            DatumKraj = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "ERP Sistem"
                        },
                        new
                        {
                            ProjekatId = 4,
                            BudzetUSD = 25000m,
                            DatumKraj = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumPocetak = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "HR Portal"
                        });
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZaposlenikId"));

                    b.Property<DateTime>("DatumZaposlenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OdjelId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlataMonthly")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OdjelId");

                    b.ToTable("Zaposlenici");

                    b.HasData(
                        new
                        {
                            ZaposlenikId = 1,
                            DatumZaposlenja = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lana@log.com",
                            Ime = "Lana",
                            OdjelId = 1,
                            PlataMonthly = 1500m,
                            Prezime = "Hodžić"
                        },
                        new
                        {
                            ZaposlenikId = 2,
                            DatumZaposlenja = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amar@log.com",
                            Ime = "Amar",
                            OdjelId = 2,
                            PlataMonthly = 2000m,
                            Prezime = "Mešić"
                        },
                        new
                        {
                            ZaposlenikId = 3,
                            DatumZaposlenja = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lejla@log.com",
                            Ime = "Lejla",
                            OdjelId = 2,
                            PlataMonthly = 1800m,
                            Prezime = "Kovač"
                        },
                        new
                        {
                            ZaposlenikId = 4,
                            DatumZaposlenja = new DateTime(2023, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emina@log.com",
                            Ime = "Emina",
                            OdjelId = 2,
                            PlataMonthly = 1700m,
                            Prezime = "Softić"
                        },
                        new
                        {
                            ZaposlenikId = 5,
                            DatumZaposlenja = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kenan@log.com",
                            Ime = "Kenan",
                            OdjelId = 1,
                            PlataMonthly = 1600m,
                            Prezime = "Alić"
                        },
                        new
                        {
                            ZaposlenikId = 6,
                            DatumZaposlenja = new DateTime(2021, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@log.com",
                            Ime = "Sara",
                            OdjelId = 3,
                            PlataMonthly = 1900m,
                            Prezime = "Begović"
                        },
                        new
                        {
                            ZaposlenikId = 7,
                            DatumZaposlenja = new DateTime(2020, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nermin@log.com",
                            Ime = "Nermin",
                            OdjelId = 1,
                            PlataMonthly = 2100m,
                            Prezime = "Hasić"
                        },
                        new
                        {
                            ZaposlenikId = 8,
                            DatumZaposlenja = new DateTime(2022, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amina@log.com",
                            Ime = "Amina",
                            OdjelId = 2,
                            PlataMonthly = 1750m,
                            Prezime = "Zornić"
                        },
                        new
                        {
                            ZaposlenikId = 9,
                            DatumZaposlenja = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "haris@log.com",
                            Ime = "Haris",
                            OdjelId = 3,
                            PlataMonthly = 2200m,
                            Prezime = "Delić"
                        },
                        new
                        {
                            ZaposlenikId = 10,
                            DatumZaposlenja = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zara@log.com",
                            Ime = "Zara",
                            OdjelId = 2,
                            PlataMonthly = 1850m,
                            Prezime = "Osmanović"
                        });
                });

            modelBuilder.Entity("Aplikacija.Models.ZaposlenikProjekat", b =>
                {
                    b.Property<int>("ZaposlenikId")
                        .HasColumnType("int");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("int");

                    b.Property<int>("SatiNaTjednu")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikId", "ProjekatId");

                    b.HasIndex("ProjekatId");

                    b.ToTable("ZaposlenikProjekti");

                    b.HasData(
                        new
                        {
                            ZaposlenikId = 1,
                            ProjekatId = 1,
                            SatiNaTjednu = 40,
                            Uloga = "Backend Developer"
                        },
                        new
                        {
                            ZaposlenikId = 2,
                            ProjekatId = 1,
                            SatiNaTjednu = 10,
                            Uloga = "HR Support"
                        },
                        new
                        {
                            ZaposlenikId = 3,
                            ProjekatId = 2,
                            SatiNaTjednu = 35,
                            Uloga = "Frontend Developer"
                        },
                        new
                        {
                            ZaposlenikId = 4,
                            ProjekatId = 2,
                            SatiNaTjednu = 20,
                            Uloga = "QA Engineer"
                        },
                        new
                        {
                            ZaposlenikId = 5,
                            ProjekatId = 3,
                            SatiNaTjednu = 30,
                            Uloga = "DevOps Engineer"
                        },
                        new
                        {
                            ZaposlenikId = 6,
                            ProjekatId = 3,
                            SatiNaTjednu = 15,
                            Uloga = "Business Analyst"
                        },
                        new
                        {
                            ZaposlenikId = 7,
                            ProjekatId = 4,
                            SatiNaTjednu = 25,
                            Uloga = "Project Manager"
                        },
                        new
                        {
                            ZaposlenikId = 8,
                            ProjekatId = 4,
                            SatiNaTjednu = 20,
                            Uloga = "UI/UX Designer"
                        },
                        new
                        {
                            ZaposlenikId = 9,
                            ProjekatId = 1,
                            SatiNaTjednu = 12,
                            Uloga = "Finance Consultant"
                        });
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.HasOne("Aplikacija.Models.Odjel", "Odjel")
                        .WithMany("Zaposlenici")
                        .HasForeignKey("OdjelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("Aplikacija.Models.ZaposlenikProjekat", b =>
                {
                    b.HasOne("Aplikacija.Models.Projekat", "Projekat")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikacija.Models.Zaposlenik", "Zaposlenik")
                        .WithMany("ZaposlenikProjekti")
                        .HasForeignKey("ZaposlenikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projekat");

                    b.Navigation("Zaposlenik");
                });

            modelBuilder.Entity("Aplikacija.Models.Odjel", b =>
                {
                    b.Navigation("Zaposlenici");
                });

            modelBuilder.Entity("Aplikacija.Models.Projekat", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });

            modelBuilder.Entity("Aplikacija.Models.Zaposlenik", b =>
                {
                    b.Navigation("ZaposlenikProjekti");
                });
#pragma warning restore 612, 618
        }
    }
}
